In [2]:
import pandas as pd
import numpy as np

In [3]:
#Load_Raw_Data
df = pd.read_csv(r"C:\Users\Sabuj Some\OneDrive\Desktop\Hoichoi Projects\Drop off Analysis\Raw Data\dropoff_raw_data_large.csv")

In [4]:
#Show_Rows
df.head()

,user_id,session_id,event_timestamp,event_name,platform,device_type,city,state,user_type,content_category,plan,plan_price,payment_method,failure_reason
0,U07368,S007368,2026-09-08 21:25:30,payment_initiated,Android,Mobile,Patna,Bihar,New,Thriller,Basic,299,Net Banking,NaN
1,U02242,S002242,2026-09-03 04:22:22,payment_initiated,iOS,Mobile,Jaipur,Rajasthan,New,Kids,Basic,299,Credit Card,NaN
2,U04952,S004952,2026-09-09 04:07:00,app_open,iOS,Mobile,Ahmedabad,Gujarat,Returning,Comedy,Basic,299,UPI,NaN
3,U08522,S008522,2026-09-15 15:15:22,paywall_viewed,Android,Mobile,Patna,Bihar,Returning,Drama,Standard,499,Debit Card,NaN
4,U04376,S004376,2026-09-11 19:02:49,paywall_viewed,Web,Desktop,Ahmedabad,Gujarat,Returning,Thriller,Basic,299,Credit Card,NaN

In [6]:
#Check_number_of_Rows_and_Column
df.shape

(33198, 14)

In [8]:
#check column name and data type

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 33198 entries, 0 to 33197
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   user_id           33198 non-null  str
 1   session_id        33198 non-null  str
 2   event_timestamp   33198 non-null  str
 3   event_name        33198 non-null  str
 4   platform          33198 non-null  str
 5   device_type       33198 non-null  str
 6   city              32999 non-null  str
 7   state             33198 non-null  str
 8   user_type         33198 non-null  str
 9   content_category  33066 non-null  str
 10  plan              33198 non-null  str
 11  plan_price        33198 non-null  int64
 12  payment_method    33066 non-null  str
 13  failure_reason    809 non-null    str
dtypes: int64(1), str(13)
memory usage: 6.6 MB

In [9]:
#first few records
df.head()

,user_id,session_id,event_timestamp,event_name,platform,device_type,city,state,user_type,content_category,plan,plan_price,payment_method,failure_reason
0,U07368,S007368,2026-09-08 21:25:30,payment_initiated,Android,Mobile,Patna,Bihar,New,Thriller,Basic,299,Net Banking,NaN
1,U02242,S002242,2026-09-03 04:22:22,payment_initiated,iOS,Mobile,Jaipur,Rajasthan,New,Kids,Basic,299,Credit Card,NaN
2,U04952,S004952,2026-09-09 04:07:00,app_open,iOS,Mobile,Ahmedabad,Gujarat,Returning,Comedy,Basic,299,UPI,NaN
3,U08522,S008522,2026-09-15 15:15:22,paywall_viewed,Android,Mobile,Patna,Bihar,Returning,Drama,Standard,499,Debit Card,NaN
4,U04376,S004376,2026-09-11 19:02:49,paywall_viewed,Web,Desktop,Ahmedabad,Gujarat,Returning,Thriller,Basic,299,Credit Card,NaN

In [10]:
#last few records
df.tail()

,user_id,session_id,event_timestamp,event_name,platform,device_type,city,state,user_type,content_category,plan,plan_price,payment_method,failure_reason
33193,U05093,S005093,2026-09-15 10:50:14,paywall_viewed,Android,Mobile,Jaipur,Rajasthan,New,Romance,Premium,699,UPI,NaN
33194,U01889,S001889,2026-09-10 03:24:00,app_open,Android,Mobile,Hyderabad,Telangana,Returning,Sports,Standard,499,Net Banking,NaN
33195,U03417,S003417,2026-09-17 05:24:58,plan_selected,Web,Desktop,Jaipur,Rajasthan,Returning,Thriller,Basic,299,Net Banking,NaN
33196,U00268,S000268,2026-09-02 23:52:58,paywall_viewed,Android,Mobile,Ahmedabad,Gujarat,New,Thriller,Premium,699,Credit Card,NaN
33197,U04775,S004775,2026-09-03 05:37:00,app_open,iOS,Mobile,Jaipur,Rajasthan,Returning,Movies,Basic,299,Net Banking,NaN

In [11]:
#Statistical Numerical Column
df.describe()

         plan_price
count  33198.000000
mean     510.115127
std      160.969975
min      299.000000
25%      299.000000
50%      499.000000
75%      699.000000
max      699.000000

In [12]:
#Check missing values in column
df.isnull().sum()

user_id                 0
session_id              0
event_timestamp         0
event_name              0
platform                0
device_type             0
city                  199
state                   0
user_type               0
content_category      132
plan                    0
plan_price              0
payment_method        132
failure_reason      32389
dtype: int64

In [16]:
#Calculate missing_value percentage for each column
missing_percentage = (df.isnull().sum() / len(df)) * 100

missing_percentage.sort_values(ascending=False)

failure_reason      97.563106
city                 0.599434
content_category     0.397614
payment_method       0.397614
user_id              0.000000
session_id           0.000000
device_type          0.000000
platform             0.000000
event_name           0.000000
event_timestamp      0.000000
user_type            0.000000
state                0.000000
plan_price           0.000000
plan                 0.000000
dtype: float64

In [18]:
#count duplicate rows

df.duplicated().sum()

np.int64(240)

In [19]:
#Remove Duplicates

df = df.drop_duplicates()

In [20]:
#Again count if duplicates are removed or not

df.duplicated().sum()

np.int64(0)

In [22]:
#now check the data type

df.dtypes

user_id               str
session_id            str
event_timestamp       str
event_name            str
platform              str
device_type           str
city                  str
state                 str
user_type             str
content_category      str
plan                  str
plan_price          int64
payment_method        str
failure_reason        str
dtype: object

In [25]:
#conver timestamp into datetime

df["event_timestamp"] = pd.to_datetime(df["event_timestamp"])

In [26]:
# Check the data type
df["event_timestamp"].dtype

dtype('<M8[us]')

In [27]:
# Check the first and last date in the dataset
print("First event:", df["event_timestamp"].min())
print("Last event:", df["event_timestamp"].max())

First event: 2026-09-01 00:04:00
Last event: 2026-09-30 23:51:17

In [28]:
#Check if there is any missing timestamps

df["event_timestamp"].isnull().sum()

np.int64(0)

In [29]:
#count records

df["event_name"].value_counts()

event_name
app_open             10001
paywall_viewed        7848
plan_selected         5734
payment_initiated     4686
payment_success       3884
payment_failed         805
Name: count, dtype: int64

In [30]:
#check different platforms

df["platform"].value_counts()

platform
Android    18001
iOS         8392
Web         6505
android       30
web           17
ios           13
Name: count, dtype: int64

In [31]:
#standadize platform names

df["platform"] = (df["platform"].astype("string").str.strip().str.title())

In [32]:
#check platform values

df["platform"].value_counts()

platform
Android    18031
Ios         8405
Web         6522
Name: count, dtype: int64[pyarrow]

In [35]:
# Check current user type values
df["user_type"].value_counts()

user_type
New          20083
Returning    12825
NEW             27
RETURNING       23
Name: count, dtype: int64

In [36]:
# Standardize user type values
df["user_type"] = (df["user_type"].astype("string").str.strip().str.title())

In [37]:
#check user_type values

df["user_type"].value_counts()

user_type
New          20110
Returning    12848
Name: count, dtype: int64[pyarrow]

In [38]:
# List of columns containing text or category values
text_columns = [
    "event_name",
    "city",
    "state",
    "content_category",
    "plan",
    "payment_method",
    "failure_reason"
]

In [39]:
# Remove unnecessary spaces from these columns
for column in text_columns:df[column] = df[column].astype("string").str.strip()

In [40]:
# Check missing values after the cleaning
df.isnull().sum()

user_id                 0
session_id              0
event_timestamp         0
event_name              0
platform                0
device_type             0
city                  199
state                   0
user_type               0
content_category      132
plan                    0
plan_price              0
payment_method        132
failure_reason      32153
dtype: int64

In [41]:
# Replace missing values with "Unknown"
df["city"] = df["city"].fillna("Unknown")
df["payment_method"] = df["payment_method"].fillna("Unknown")
df["content_category"] = df["content_category"].fillna("Unknown")

In [42]:
# Confirm the missing values have been handled
df.isnull().sum()

user_id                 0
session_id              0
event_timestamp         0
event_name              0
platform                0
device_type             0
city                    0
state                   0
user_type               0
content_category        0
plan                    0
plan_price              0
payment_method          0
failure_reason      32153
dtype: int64

In [43]:
# Check subscription plans
df["plan"].value_counts()

plan
Premium     11633
Standard    11509
Basic        9816
Name: count, dtype: int64[pyarrow]

In [44]:
# Check payment methods
df["payment_method"].value_counts()

payment_method
UPI            14816
Credit Card     5649
Debit Card      5498
Net Banking     4011
Wallet          2852
Unknown          132
Name: count, dtype: int64[pyarrow]

In [45]:
# Check why payments failed
df["failure_reason"].value_counts()

failure_reason
Bank Declined         209
Gateway Timeout       166
Technical Error       151
Insufficient Funds    149
User Abandoned        130
Name: count, dtype: int64[pyarrow]

In [46]:
# Arrange each user's events in chronological order
df = df.sort_values( by=["user_id", "event_timestamp"]).reset_index(drop=True)

In [47]:
# Check the journey of one user
df[df["user_id"] == "U00001"]

,user_id,session_id,event_timestamp,event_name,platform,device_type,city,state,user_type,content_category,plan,plan_price,payment_method,failure_reason
0,U00001,S000001,2026-09-26 19:54:00,app_open,Android,Mobile,Patna,Bihar,Returning,Movies,Standard,499,UPI,<NA>
1,U00001,S000001,2026-09-26 19:56:16,paywall_viewed,Android,Mobile,Patna,Bihar,Returning,Movies,Standard,499,UPI,<NA>
2,U00001,S000001,2026-09-26 19:57:28,plan_selected,Android,Mobile,Patna,Bihar,Returning,Movies,Standard,499,UPI,<NA>

In [48]:
# Final check after cleaning

print("Number of rows:", len(df))
print("Number of columns:", len(df.columns))
print("Unique users:", df["user_id"].nunique())
print("Duplicate rows:", df.duplicated().sum())

print("\nMissing values:")
print(df.isnull().sum())

Number of rows: 32958
Number of columns: 14
Unique users: 10000
Duplicate rows: 2

Missing values:
user_id                 0
session_id              0
event_timestamp         0
event_name              0
platform                0
device_type             0
city                    0
state                   0
user_type               0
content_category        0
plan                    0
plan_price              0
payment_method          0
failure_reason      32153
dtype: int64

In [49]:
# Save the cleaned dataset as a new CSV file
df.to_csv(r"C:\Users\Sabuj Some\OneDrive\Desktop\Hoichoi Projects\Drop off Analysis\Raw Data\dropoff_cleaned_data.csv", index=False)

print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.